### ISSUE TITLE
504 timeout

### ISSUE THREAD

**Issue by ghost** [homanp/vercel-langchain#1]
I am using Vercel to deploy my project, which contains a chain of processes interacting with OpenAI and Pinecone services. While the API works fine on my local host, when deployed to Vercel, request timeouts occurred after 1 minute, resulting in 504 gateway timeout errors.
Vercel mentioned that using serverless functions for this issue is not recommended; use [Edge Functions] instead, which have other limitations. I tried to fix the problem myself but could not find a solution.
<img width="1137" alt="截圖 2023-03-24 下午7 43 23" src="https://user-images.githubusercontent.com/127195550/227727596-0d8248d3-c990-4326-8b39-e6fe772a0a8d.png">

**Comment by homanp** [comment]
Thanks for reporting, my ask what code you are running that takes approx 1 minute to return a response? 

I mean if it is a chat response those usually go faster. 

Could you post some code from your endpoint I could take a look at? 

Thanks.

**Comment by ghost** [comment]
Hi, I am trying to deploy https://github.com/mayooear/gpt4-pdf-chatbot-langchain, which involves a chain of processes interacting with OpenAI and Pinecone services. While the API works fine on my localhost, I have been experiencing request timeouts after 1 minute when deployed on Vercel, resulting in 504 Gateway Timeout errors.

**Comment by homanp** [comment]
Yeah, there are hard limits Vercel set on their API/edge functions. 

Perhaps the best approach here would be to split the logic a bit run them separately?

**Comment by ghost** [comment]
I am deeply grateful for your kindness support. Thank you from the bottom of my heart.
